version: "3"

services:
  mongodb:
    image: mongo:4.2
    environment:
      MONGO_INITDB_DATABASE:
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_ROOT_PASSWORD:
      MONGODB_USERNAME:
      MONGODB_PASSWORD:
      MONGODB_DB:
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
      - ./mongodb:/docker-entrypoint-initdb.d:ro

  application:
    build: .
    image: movieflix
    command: --reload
    restart: always
    environment:
      MONGODB_HOST: mongodb
      MONGODB_PORT: 27017
      MONGODB_DB:
      MONGODB_USERNAME:
      MONGODB_PASSWORD:
      MAX_WORKERS:
      PORT: ${PORT:-5000}
      SECRET_KEY: ${SECRET_KEY:-supersecretkey}
    ports:
      - 5000:${PORT:-5000}
    volumes:
      - ./src:/app/src
    depends_on:
      - mongodb
